# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-22 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='Lattitude')),
                ('lon', models.FloatField(verbose_name='Longitude')),
                ('region', models.IntegerField(verbose_name='Region Number')),
                ('score', models.IntegerField(verbose_name='Score')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='Lattitude')),
                ('lon', models.FloatField(verbose_name='Longitude')),
            ],
        ),
    ]
