# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-22 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.RemoveField(
            model_name='regions',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='regions',
            name='region',
        ),
        migrations.AddField(
            model_name='regions',
            name='country_short',
            field=models.CharField(default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='regions',
            name='formatted_address',
            field=models.CharField(default='NONE', max_length=150),
        ),
        migrations.AddField(
            model_name='regions',
            name='lng',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='regions',
            name='place',
            field=models.CharField(default='NONE', max_length=150),
        ),
        migrations.AlterField(
            model_name='regions',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='regions',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
