# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-22 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20170422_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(default='NONE', max_length=150)),
                ('lat', models.FloatField(default=0.0)),
                ('lng', models.FloatField(default=0.0)),
                ('formatted_address', models.CharField(default='NONE', max_length=150)),
                ('country_short', models.CharField(default='NONE', max_length=10)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
